apiVersion: 'v1'
kind: pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: vege1:v1.0.2
    ports:
  - containerport: 3000
    containers:
  - name: nginx
    image: nginx
    ports:
    - containerport: 80